[package]
name = "beacon-kit-verifier"
version = "0.1.1"
edition = "2021"
authors = ["Polytope Labs"]
publish = false

[dependencies]
hex-literal = { workspace = true }
sync-committee-primitives = { workspace = true, default-features = false }
sync-committee-verifier = { workspace = true, default-features = false }
log = { workspace = true, default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main", default-features = false }
bls = { workspace = true }
codec = { workspace = true, features = ["derive"] }
primitive-types = { workspace = true, features = [
    "serde_no_std",
    "impl-codec",
] }
thiserror = { workspace = true}


[features]
default = ["std"]
std = [
    "ssz-rs/std",
    "ssz-rs/default",
    "ssz-rs/serde",
    'codec/std',
    "log/std",
    "primitive-types/std",
    "sync-committee-primitives/std",
    "log/std",
    "bls/std",
    "sync-committee-verifier/std",
]

