[package]
name = "tesseract-evm"
version = "0.1.0"
edition = "2021"
description = "EVM primitives for ISMP messaging relay"
authors = ["Polytope Labs <hello@polytope.technology>"]

[build-dependencies]
anyhow = "1.0.75"
ethers-contract-abigen = { workspace = true }


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
anyhow = "1.0.75"
primitive-types = "0.12.1"
futures = "0.3.28"
async-trait = "0.1.71"
parking_lot = "0.12.1"
serde_json = "1.0.105"
hex-literal = { version ="0.4.1"}
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
sp-core = { workspace = true,  features = ["full_crypto"] }
log = "0.4.19"
ethers = { workspace = true, features = ["rustls"] }
ethabi = { version = "18.0.0", features = ["rlp", "full-serde"], default-features = false }
tokio = { version = "1.32.0", features = ["macros", "sync"] }
tokio-stream = "0.1.14"
frame-support = { workspace = true }
reqwest-retry = "0.3.0"
reqwest-middleware = "0.2.4"
async-recursion = "1.0.5"

ismp-solidity-abi.workspace = true
beefy-verifier-primitives.workspace = true
pallet-ismp.workspace = true
ismp.workspace = true
pallet-ismp-rpc.workspace = true
geth-primitives.workspace = true
ismp-sync-committee.workspace = true
ethereum-trie.workspace = true
mmr-primitives.workspace = true
evm-common.workspace = true
sp-mmr-primitives.workspace = true

tesseract-primitives = { path = "../../primitives" }
debounced = { git= "https://github.com/polytope-labs/debounced", branch = "main"}


merkle-mountain-range = { workspace = true }
reconnecting-jsonrpsee-ws-client.workspace = true
jsonrpsee = { version = "0.21", features = ["ws-client"]}
pallet-ismp-host-executive.workspace = true

[dev-dependencies]
alloy-rlp = "0.3.2"
alloy-rlp-derive = "0.3.2"
alloy-primitives = { version = "0.3.1", features = ["rlp"] }
hex = "0.4.3"
dotenv = "0.15.0"


[features]
testing = []
