[package]
name = "pallet-ismp-relayer"
version = "0.1.1"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]
description = "Pallet for tracking relayer deliveries and managing their associated fees"
publish = false


[dependencies]
pallet-ismp = { workspace = true }
evm-state-machine = { workspace = true }
pallet-ismp-host-executive = { workspace = true }
pallet-hyperbridge = { workspace = true }
ismp = { workspace = true }
crypto-utils = { workspace = true }

# crates.io
log = { workspace = true, default-features = false }
hashbrown = { version = "0.14.3" }
codec = { workspace = true }
scale-info = { workspace = true }
alloy-rlp = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp-derive = { workspace = true }
ethabi = { workspace = true }
anyhow = { workspace = true }

[dependencies.polkadot-sdk]
workspace = true
features = ["frame-support", "frame-system", "sp-runtime", "sp-core", "sp-io"]

[dev-dependencies]
pallet-ismp = { workspace = true, features = ["testing"] }
ethereum-triedb = { workspace = true }
trie-db = { workspace = true }
hash-db = { workspace = true }
ismp-bsc = { workspace = true }
ismp-sync-committee = { workspace = true }
substrate-state-machine = { workspace = true }
hex = "0.4.3"

[dev-dependencies.polkadot-sdk]
workspace = true
features = ["pallet-timestamp", "pallet-balances", "sp-trie"]

[features]
default = ["std"]
std = [
    "codec/std",
    "polkadot-sdk/std",
    "log/std",
    "scale-info/std",
    "ismp/std",
    "pallet-ismp/std",
    "pallet-hyperbridge/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "ethabi/std",
    "evm-state-machine/std",
    "pallet-ismp-host-executive/std",
    "anyhow/std",
    "crypto-utils/std"
]
try-runtime = ["polkadot-sdk/try-runtime"]
