[package]
name = "beefy-prover"
version = "0.1.1"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]
description = "Prover for the BEEFY consensus client"
publish = false


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow.workspace = true
primitive-types = { workspace = true, features = ["codec"] }
codec = { workspace = true, features = ["derive"], default-features = true }
derive_more = { workspace = true, features = ["from"], default-features = true }
rs_merkle = { git = "https://github.com/polytope-labs/rs-merkle", branch = "seun/2d-merkle-proofs" }
hex-literal = "0.4.1"
hex = { version = "0.4.3" }

subxt = { workspace = true, default-features = true }
subxt-core = { workspace = true, default-features = true }
beefy-verifier-primitives = { workspace = true }
merkle-mountain-range = { workspace = true }
indicatif = "0.18.0"
futures = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
log = { workspace = true }

[dev-dependencies]
subxt-utils = { workspace = true, default-features = true }
tokio = { version = "1.35.1", features = ["fs", "macros", "rt-multi-thread"] }

[dependencies.polkadot-sdk]
workspace = true
default-features = true
features = [
    "sp-runtime",
    "sp-io",
    "pallet-beefy-mmr",
    "sp-mmr-primitives",
    "sp-consensus-beefy",
    "sp-trie",
    "sp-storage",
    "frame-support",
    "mmr-rpc",
]

[features]
local = []
