[package]
name = "beefy-prover"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]
description = "Prover for the BEEFY consensus client"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = "1.0.72"
primitive-types = { version = "0.12.0", features = ["codec"] }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
derive_more = { version = "0.99.17", features = ["from"]  }
rs_merkle = { git = "https://github.com/polytope-labs/rs-merkle", branch = "seun/2d-merkle-proofs" }

# substrate
sp-runtime = { workspace = true, features = ["default"] }
sp-storage =  { workspace = true, features = ["default"] }
sp-io = { workspace = true, features = ["default"] }
frame-support = { workspace = true, features = ["default"]}
pallet-beefy-mmr = { workspace = true, features = ["default"] }
sp-mmr-primitives = { workspace = true, features = ["default"] }
sp-consensus-beefy = { workspace = true, features = ["default"] }
sp-trie = { workspace = true, features = ["default"] }
mmr-rpc = { workspace = true }

# Optional deps
subxt = { version = "0.30.1", features = ["substrate-compat"] }
serde_json = { version = "1.0.74" }

hex = { version = "0.4.3" }
beefy-verifier-primitives = {  path = "../primitives" }

