[package]
name = "ismp-polygon-pos"
version = "0.1.0"
edition = "2021"
description = "ISMP Consensus Client for the Polygon POS Network's Consensus Protocol"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
anyhow = { version = "1.0.75", default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

ismp = { path = "../core", default-features = false }
polygon-pos-verifier = { path = "../../consensus/polygon-pos/verifier", default-features = false }
geth-primitives = { path = "../../consensus/geth-primitives", default-features = false }
pallet-ismp = { path = "../pallet", default-features = false }
ismp-sync-committee = {path = "../sync-committee", default-features = false}

frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "anyhow/std",
    "sp-core/std",
    "codec/std",
    "scale-info/std",
    "polygon-pos-verifier/std",
    "frame-system/std",
    "frame-support/std",
    "sp-runtime/std",
    "ismp-sync-committee/std",
    "pallet-ismp/std",
    "ismp/std",
    "geth-primitives/std"
]
