[package]
name = "pallet-ismp-host-executive"
version = "0.1.0"
edition = "2021"
description = "The host executive is responsible for tracking all connected hosts and is responsible for updating them"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
# substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }

# polytope labs
ismp = { workspace = true }
pallet-ismp = { workspace = true }

alloy-rlp-derive = { workspace = true }
alloy-rlp = { workspace = true }
alloy-primitives = { workspace = true }

# crates.io
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = [
    "derive",
] }
anyhow = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-core/std",
    "alloy-rlp/std",
    "alloy-primitives/std",
    "ismp/std",
    "anyhow/std",
    "pallet-ismp/std",
]

try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "sp-runtime/try-runtime",
]
