[package]
name = "hyperclient"
version = "0.3.1"
edition = "2021"
description = "The hyperclient is a library for managing (in-flight) ISMP requests"
repository = "https://github.com/polytope-labs/hyperbridge"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.90" }
subxt = { version = "0.30.1", default-features = false }
getrandom = { version = "0.2", default-features = false, features = ["js"] }
anyhow = "1.0.75"
hex-literal = { version = "0.4.1" }
serde-wasm-bindgen = { version = "0.6.3", default-features = false }
serde = { version = "1.0.196", features = ["derive"], default-features = false }
wasm-bindgen-futures = "0.4.40"
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false }
futures = "0.3.30"
wasm-streams = "0.4.0"
tokio = { version = "1.35.1", features = ["macros"]  }
wasm-bindgen-test = "0.3.41"
js-sys = "0.3.68"
web-sys = "0.3.68"
wasm-timer = { package = "fluvio-wasm-timer", version = "0.2.5" }
hashbrown = { version = "0.14.3", features = ["serde"] }
primitive-types = { version = "0.12.2", default-features = false, features = ["serde"] }
tracing = { version = "0.1.40", default-features = false }

ethers = { workspace = true, features = ["ws"] }

ismp = { path = "../ismp/core", default-features = false }
ismp-solidity-abi = { path = "../../evm/abi", default-features = false }

[dependencies.reconnecting-jsonrpsee-ws-client]
git = "https://github.com/niklasad1/reconnecting-jsonrpsee-ws-client"
rev = "84fd8400cac12babd1be7c337dc1a8d14ce0c101"
default-features = false

[features]
default = ["std"]
wasm = ["subxt/web", "subxt/jsonrpsee", "reconnecting-jsonrpsee-ws-client/web"]
std = ["subxt/native", "subxt/jsonrpsee", "reconnecting-jsonrpsee-ws-client/native"]

[dev-dependencies]
json = { package = "serde_json", version = "1.0.114", default-features = false }
wasm-bindgen-test = "0.3.24"
tracing-wasm = "0.2.1"
console_error_panic_hook = "0.1.7"
hex = { version = "0.4.3", default-features = false }