[package]
name = "geth-primitives"
version = "0.1.1"
edition = "2021"
description = "Primitives for geth client"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[dependencies]
anyhow = { workspace = true, default-features = false }
alloy-rlp = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp-derive.workspace = true
codec = { workspace = true }
ethabi = { workspace = true }
ismp = { workspace = true }
scale-info = { workspace = true }
ethers-core = { workspace = true, optional = true }
primitive-types = { workspace = true }

[features]
default = ["std"]
std = [
    "anyhow/std",
    "codec/std",
    "ismp/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "ethabi/std",
    "scale-info/std",
    "ethers-core",
    "primitive-types/std"
]
