[package]
name = "pallet-ismp-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
# substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
pallet-ismp = { workspace = true }
ismp-sync-committee = { workspace = true }
ismp-host-executive = { workspace = true }

# polytope labs
ismp = { workspace = true }

# crates.io
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false }
log = { version = "0.4.17", default-features = false }
hashbrown = { version = "0.14.3" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
alloy-rlp = { version = "0.3.2", default-features = false }
alloy-primitives = { version = "0.6.0", default-features = false, features = ["rlp"] }
alloy-rlp-derive = "0.3.2"
ethabi = { version = "18.0.0", features = ["rlp", "parity-codec"], default-features = false }


[dev-dependencies]
pallet-ismp = { path = "..", features = [ "testing" ] }
pallet-timestamp = { workspace = true }
pallet-balances = { workspace = true }
ethereum-trie = { path = "../../../trees/ethereum" }
trie-db = { workspace = true }
hash-db = { workspace = true }
ismp-bsc = { workspace = true }
ismp-sync-committee = { workspace = true }
sp-trie = { workspace = true }
substrate-state-machine = { workspace = true }
hex = "0.4.3"

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "scale-info/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-core/std",
    "sp-io/std",
    "ismp/std",
    "pallet-ismp/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "ethabi/std",
    "ismp-sync-committee/std",
    "ismp-host-executive/std"
]

try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
