[package]
name = "ismp-parachain"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# crates.io
serde = { version = "1.0.136", features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
hex-literal = "0.4.1"
primitive-types = { version = "0.12.1", default-features = false }

# polytope labs
ismp = { path = "../primitives/ismp-rs", default-features = false }
ismp-primitives = { path = "../primitives", default-features = false }
pallet-ismp = { path = "../core", default-features = false }

# substrate
frame-support = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
frame-system = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-trie = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-inherents = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-io = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-consensus-aura = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }

# cumulus
parachain-system = { package = "cumulus-pallet-parachain-system", git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0",  default-features = false }
cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }

# local
substrate-state-machine = { path = "../../state-machine", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "parachain-system/std",
    "cumulus-primitives-core/std",
    "ismp/std",
    "sp-trie/std",
    "sp-consensus-aura/std",
    "sp-runtime/std",
    "sp-io/std",
    "sp-inherents/std",
    "primitive-types/std",
    "ismp-primitives/std",
    "pallet-ismp/std",
    "serde",
    "substrate-state-machine/std"
]
