[11155111]
endpoint_url = "${SEPOLIA_RPC_URL}"

[11155111.address]
HOST = "0x2EdB74C269948b60ec1000040E104cef0eABaae8"

[11155111.bool]
is_mainnet = false
7702 = true

[421614]
endpoint_url = "${ARBITRUM_SEPOLIA_RPC_URL}"

[421614.address]
HOST = "0x3435bD7e5895356535459D6087D1eB982DAd90e7"

[421614.bool]
is_mainnet = false
7702 = true

[11155420]
endpoint_url = "${OPTIMISM_SEPOLIA_RPC_URL}"

[11155420.address]
HOST = "0x6d51b678836d8060d980605d2999eF211809f3C2"

[11155420.bool]
is_mainnet = false
7702 = true

[84532]
endpoint_url = "${BASE_SEPOLIA_RPC_URL}"

[84532.address]
HOST = "0xD198c01839dd4843918617AfD1e4DDf44Cc3BB4a"

[84532.bool]
is_mainnet = false
7702 = true

[97]
endpoint_url = "${BSC_TESTNET_RPC_URL}"

[97.address]
HOST = "0x8Aa0Dea6D675d785A882967Bf38183f6117C09b7"

[97.bool]
is_mainnet = false
7702 = true

[10200]
endpoint_url = "${GNOSIS_CHIADO_RPC_URL}"

[10200.address]
HOST = "0x58A41B89F4871725E5D898d98eF4BF917601c5eB"

[10200.bool]
is_mainnet = false
7702 = true

[80002]
endpoint_url = "${POLYGON_AMOY_RPC_URL}"

[80002.address]
HOST = "0x9a2840D050e64Db89c90Ac5857536E4ec66641DE"

[80002.bool]
is_mainnet = false
7702 = true

[1328]
endpoint_url = "${SEI_TESTNET_RPC_URL}"

[1328.address]
HOST = "0x0957552283Fb9f3d82F2a3e42135Dfe4F6c53776"
PING = "0x73D7D9cB328a1b8ff70b735b9d554c42BAFcC5E6"
TOKEN_FAUCET = "0xc6301D4959Bd66A8F4ed142420F397E9739860a4"
CALL_DISPATCHER = "0xb279b11BeAe094E9119fc69cC80E33Dbc9407be2"
TOKEN_GATEWAY = "0xcBe0658fB5902d0565a4cBdfe5826C21F282fF58"
INTENT_GATEWAY = "0xa89dbd9E1614Ed930625A3B27b98687B0a727F5D"
HANDLER = "0x9E6C1bde8B04AFEe3747439B55EaA5200D425d8f"
FEE_TOKEN = "0x1452D37b4B0d28dd2fa77b2F0bC784274db7b3F7"

[1328.bool]
is_mainnet = false
7702 = false

[420420417]
endpoint_url = "${POLKADOT_TESTNET_URL}"

[420420417.address]
HOST = "0xbb26e04A71e7c12093e82b83BA310163Eac186fa"
PING = "0x11e24eB75b27A4a48ADA1C5FB036Fa8e718b32B4"
TOKEN_FAUCET = "0x9A769357766692E7656400538B11F8Ef3FD36fb4"
HANDLER = "0x8B31A195c98Ead34Cf463A66F52942B6145A68A2"
FEE_TOKEN = "0x0Dc440CF87830f0aF564eB8b62b454B7e0c68a4b"
CALL_DISPATCHER = "0xD33E4238339860A8a8bFc889C7d2A91F51D657A0"
TOKEN_GATEWAY = "0x1c1e5BE83dF4A54C7a2230C337E4A3E8B7354B1c"
INTENT_GATEWAY = "0x606BA811AA6cB424ce2108E8977C5284686F0D1f"

[420420417.bool]
is_mainnet = false
7702 = false
