[1]
endpoint_url = "${ETHEREUM_RPC_URL}"

[1.address]
UNISWAP_V2 = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
FEE_TOKEN = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
HOST = "0x792A6236AF69787C40cF76b69B4c8c7B28c4cA20"
CALL_DISPATCHER = "0xC71251c8b3e7B02697A84363Eef6DcE8DfBdF333"
INTENT_GATEWAY = "0x1A4ee689A004B10210A1dF9f24A387Ea13359aCF"

[1.bool]
is_mainnet = true

[42161]
endpoint_url = "${ARBITRUM_RPC_URL}"

[42161.address]
UNISWAP_V2 = "0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24"
FEE_TOKEN = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
HOST = "0xE05AFD4Eb2ce6d65c40e1048381BD0Ef8b4B299e"
CALL_DISPATCHER = "0xC71251c8b3e7B02697A84363Eef6DcE8DfBdF333"
INTENT_GATEWAY = "0x1A4ee689A004B10210A1dF9f24A387Ea13359aCF"
SWAP_ROUTER= "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"
QUOTER = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"

[42161.bool]
is_mainnet = true

[10]
endpoint_url = "${OPTIMISM_RPC_URL}"

[10.address]
UNISWAP_V2 = "0x4A7b5Da61326A6379179b40d00F57E5bbDC962c2"
FEE_TOKEN = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
HOST = "0x78c8A5F27C06757EA0e30bEa682f1FD5C8d7645d"
SWAP_ROUTER = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"
QUOTER = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"

[10.bool]
is_mainnet = true

[8453]
endpoint_url = "${BASE_RPC_URL}"

[8453.address]
UNISWAP_V2 = "0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24"
FEE_TOKEN = "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
HOST = "0x6FFe92e4d7a9D589549644544780e6725E84b248"
CALL_DISPATCHER = "0xC71251c8b3e7B02697A84363Eef6DcE8DfBdF333"
INTENT_GATEWAY = "0x1A4ee689A004B10210A1dF9f24A387Ea13359aCF"

[8453.bool]
is_mainnet = true

[56]
endpoint_url = "${BSC_RPC_URL}"

[56.address]
UNISWAP_V2 = "0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24"
FEE_TOKEN = "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3"
HOST = "0x24B5d421Ec373FcA57325dd2F0C074009Af021F7"
CALL_DISPATCHER = "0xC71251c8b3e7B02697A84363Eef6DcE8DfBdF333"
INTENT_GATEWAY = "0x1A4ee689A004B10210A1dF9f24A387Ea13359aCF"

[56.bool]
is_mainnet = true

[100]
endpoint_url = "${GNOSIS_RPC_URL}"

[100.address]
UNISWAP_V2 = "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
FEE_TOKEN = "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
HOST = "0x50c236247447B9d4Ee0561054ee596fbDa7791b1"

[100.bool]
is_mainnet = true

[1868]
endpoint_url = "${SONEIUM_RPC_URL}"

[1868.address]
UNISWAP_V2 = "0x0000000000000000000000000000000000000000"
FEE_TOKEN = "0xbA9986D2381edf1DA03B0B9c1f8b00dc4AacC369"
HOST = "0x7F0165140D0f3251c8f6465e94E9d12C7FD40711"
UNIVERSAL_ROUTER = "0x4cded7edf52c8aa5259a54ec6a3ce7c6d2a455df"
V4_QUOTER = "0x3972c00f7ed4885e145823eb7c655375d275a1c5"
WETH = "0x4200000000000000000000000000000000000006"

[1868.bool]
is_mainnet = true

[130]
endpoint_url = "${UNICHAIN_RPC_URL}"

[130.address]
HOST = "0x2A17C1c3616Bbc33FCe5aF5B965F166ba76cEDAf"
CALL_DISPATCHER = "0xC71251c8b3e7B02697A84363Eef6DcE8DfBdF333"
INTENT_GATEWAY = "0x1A4ee689A004B10210A1dF9f24A387Ea13359aCF"
SWAP_ROUTER = "0x73855d06de49d0fe4a9c42636ba96c62da12ff9c"
QUOTER = "0x385a5cf5f83e99f7bb2852b6a19c3538b9fa7658"

[130.bool]
is_mainnet = true

[137]
endpoint_url = "${POLYGON_RPC_URL}"

[137.address]
UNISWAP_V2 = "0xedf6066a2b290C185783862C7F4776A2C8077AD1"
FEE_TOKEN = "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063"
HOST = "0xD8d3db17C1dF65b301D45C84405CcAC1395C559a"
CALL_DISPATCHER = "0xC71251c8b3e7B02697A84363Eef6DcE8DfBdF333"
INTENT_GATEWAY = "0x1A4ee689A004B10210A1dF9f24A387Ea13359aCF"

[137.bool]
is_mainnet = true

[57073]
endpoint_url = "${INKCHAIN_RPC_URL}"

[57073.address]
UNISWAP_V2 = "0x0000000000000000000000000000000000000000"
FEE_TOKEN = "0x0000000000000000000000000000000000000000"
HOST = "0x0000000000000000000000000000000000000000"

[57073.bool]
is_mainnet = true

[1329]
endpoint_url = "${SEI_RPC_URL}"

[1329.address]
FEE_TOKEN = "0xe15fC38F6D8c56aF07bbCBe3BAf5708A2Bf42392"
WETH = "0xE30feDd158A2e3b13e9badaeABaFc5516e95e8C7"
SWAP_ROUTER = "0x11DA6463D6Cb5a03411Dbf5ab6f6bc3997Ac7428"
QUOTER = "0x38F759cf0Af1D0dcAEd723a3967A3B658738eDe9"

[1329.bool]
is_mainnet = true
