[package]
name = "ismp-bsc-pos"
version = "0.1.0"
edition = "2021"
description = "ISMP Consensus Client for the BNB POS Network's Consensus Protocol"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
log = { version = "0.4.17", default-features = false }
anyhow = { version = "1.0.75", default-features = false }
sp-core = {version = "27.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

ismp = { path = "../core", default-features = false }
bsc-pos-verifier = { path = "../../consensus/bsc-pos/verifier", default-features = false }
pallet-ismp = { path = "../pallet", default-features = false }
ismp-sync-committee = {path = "../sync-committee", default-features = false}
sync-committee-primitives = { path= "../../consensus/sync-committee/primitives", default-features = false }
frame-support = { default-features = false, workspace = true }
frame-system = { default-features = false, workspace = true }
sp-runtime = { default-features = false, workspace = true }
geth-primitives = { path = "../../consensus/geth-primitives", default-features = false }

[features]
default = ["std"]
std = [
    "log/std",
    "anyhow/std",
    "sp-core/std",
    "codec/std",
    "scale-info/std",
    "bsc-pos-verifier/std",
    "frame-system/std",
    "frame-support/std",
    "sp-runtime/std",
    "ismp-sync-committee/std",
    "pallet-ismp/std",
    "ismp/std",
    "sync-committee-primitives/std",
]
