[package]
name = "tesseract-messaging"
version = "0.1.0"
edition = "2021"
description = "Chain agnostic ISMP request/response relay"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[dependencies]
anyhow = { workspace = true }
tracing = "0.1.40"
percentage = "0.1.0"
futures = "0.3.28"
tokio = { workspace = true, features = ["full"] }
sp-core = { workspace = true, features = ["full_crypto"] }
hex = "0.4.3"
itertools = "0.13.0"
tokio-stream = { workspace = true }

ismp = { workspace = true, default-features = true }
pallet-ismp = { workspace = true, default-features = true }
pallet-state-coprocessor = { workspace = true, default-features = true }

transaction-fees = { workspace = true }
tesseract-primitives = { workspace = true }
ismp-solidity-abi = { workspace = true, default-features = true }
primitive-types = { workspace = true, default-features = true }

[dependencies.polkadot-sdk]
workspace = true
default-features = true
features = ["sc-service"]
