[package]
edition = "2021"
name = "ismp-runtime-api"
version = "0.1.0"
authors = ["Polytope Labs <hello@polytope.technology>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
pallet-ismp = { path = "../pallet", default-features = false }
ismp = { package = "ismp", path = "../core", default-features = false }
serde = { version = "1.0.136", features = ["derive"], optional = true }

[dependencies.codec]
package = "parity-scale-codec"
version = "3.0.0"
features = ["derive"]
default-features = false

[features]
default = ['std']
std = ['sp-api/std', 'sp-std/std', 'codec/std', "pallet-ismp/std", "ismp/std", "serde"]
