[package]
name = "ismp-beacon-kit"
version = "0.1.0"
edition = "2021"
description = "ISMP Consensus Client for BeaconKit Consensus Protocol"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[dependencies]
log = { workspace = true, default-features = false, optional = true }
anyhow = { workspace = true, default-features = false, optional = true }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
primitive-types = { workspace = true, default-features = false }
pallet-ismp-host-executive = { workspace = true, default-features = false }
sp-io = { workspace = true }
ismp = { workspace = true, default-features = false }
tendermint-verifier = { workspace = true, default-features = false }
tendermint-primitives = { workspace = true, default-features = false }
geth-primitives = { workspace = true, default-features = false }
codec = { workspace = true, default-features = false }
evm-state-machine = { workspace = true }
sync-committee-primitives = { workspace = true, default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main", default-features = false }
sha2 = { version = "0.10", default-features = false }
base64 = { version = "0.22.1", default-features = false }
cometbft = { workspace = true }

[features]
default = ["std"]
std = [
    "log/std",
    "anyhow/std",
    "scale-info/std",
    "primitive-types/std",
    "pallet-ismp-host-executive/std",
    "sp-io/std",
    "ismp/std",
    "tendermint-verifier/std",
    "tendermint-primitives/std",
    "geth-primitives/std",
    "codec/std",
    "evm-state-machine/std",
    "sync-committee-primitives/std",
    "ssz-rs/default",
    "ssz-rs/serde",
    "base64/std",
    "cometbft/std"
]
