[package]
name = "sync-committee-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]

[dependencies]
sync-committee-primitives = { path= "../primitives", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main", default-features = false }
log = { version = "0.4.17", default-features = false }
anyhow = { version = "1.0.75", default-features = false }
ark-ec = { version = "0.4.2", default-features = false }
ark-bls12-381 = { version = "0.4.0", default-features = false, features = ["curve"] }
bls = { package = "bls_on_arkworks", version = "0.2.2", default-features = false }

[features]
default = ["std"]
std = [
    "ssz-rs/std",
    "log/std",
    "sync-committee-primitives/std",
    "log/std",
    "anyhow/std",
    "ark-ec/std",
    "ark-bls12-381/std",
    "bls/std"
]
sepolia = ["sync-committee-primitives/sepolia"]
mainnet = ["sync-committee-primitives/mainnet"]

[dev-dependencies]
hex = "0.4.3"
