[package]
name = "pharos-verifier"
version = "0.1.0"
edition = "2021"
description = "Pharos consensus verifier for light client"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[dependencies]
pharos-primitives = { workspace = true, default-features = false }
crypto-utils = { workspace = true, default-features = false }
geth-primitives = { workspace = true, default-features = false }
ismp = { workspace = true, default-features = false }
bls = { workspace = true }
log = { workspace = true, default-features = false }
anyhow = { workspace = true, default-features = false }
thiserror = { workspace = true }
primitive-types = { workspace = true }

[features]
default = ["std"]
std = [
    "pharos-primitives/std",
    "crypto-utils/std",
    "geth-primitives/std",
    "ismp/std",
    "log/std",
    "anyhow/std",
    "bls/std",
    "primitive-types/std",
]

[dependencies.hex]
version = "0.4.3"
default-features = false
features = ["alloc"]

[dev-dependencies]
hex-literal = { workspace = true, default-features = true }
