[package]
name = "pharos-primitives"
version = "0.1.0"
edition = "2021"
description = "Primitive types for Pharos consensus verifier"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[dependencies]
codec = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rlp-derive = { workspace = true }
crypto-utils = { workspace = true, default-features = false }
primitive-types = { workspace = true, features = ["serde_no_std", "impl-codec"] }
hex-literal = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }
sp-io = { workspace = true, default-features = false }
anyhow = { workspace = true, default-features = false }
geth-primitives = { workspace = true, default-features = false }
ismp = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "crypto-utils/std",
    "primitive-types/std",
    "anyhow/std",
    "sp-io/std",
    "serde",
    "geth-primitives/std",
    "ismp/std",
]
