[package]
name = "tesseract-fisherman"
version = "0.1.1"
edition = "2021"
description = "A process that checks for malicious consensus updates"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
anyhow = { workspace = true }
log = "0.4.17"
futures = "0.3.28"
tracing = "0.1.40"
tokio = { workspace = true, features = ["full"] }
sp-core = { workspace = true, features = ["full_crypto"] }

ismp = { workspace = true }
pallet-ismp = { workspace = true }

tesseract-primitives = { workspace = true }

[dependencies.polkadot-sdk]
workspace = true
default-features = true
features = ["sc-service"]
