[package]
name = "tesseract-polygon"
version = "0.1.0"
edition = "2021"
description = "Polygon consensus relayer for tesseract"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
anyhow = {workspace = true, default-features = false}
async-trait = "0.1.88"
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
ismp = { workspace = true }
ismp-polygon = { workspace = true }
log = { workspace = true, default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tendermint-primitives = { workspace = true }
tendermint-verifier = { workspace = true }
tesseract-evm = { workspace = true }
tesseract-primitives = { workspace = true }
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
cometbft = { workspace = true }
cometbft-rpc = { workspace = true }
geth-primitives = { workspace = true }
reqwest = { version = "0.11", features = ["json"] }
ethers = { workspace = true, features = ["ws", "default"] }
base64 = { version = "0.21" }
sha2 = { version = "0.10.7" }
sha3 = { version = "0.10" }
ics23 = { workspace = true, default-features = false }
tendermint-ics23-primitives = { workspace = true, default-features = false }
prost = {workspace = true, default-features = false }
ibc = { workspace = true }
ibc-proto = { workspace = true }
