[package]
name = "tesseract-substrate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.164", features = ["derive"] }
anyhow = "1.0.75"
futures = "0.3.28"
async-trait = "0.1.71"
parking_lot = "0.12.1"
hex-literal = { version = "0.4.1" }
subxt = { version = "0.30.1", features = ["substrate-compat"] }
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
sp-core = { version = "21.0.0", features = ["full_crypto"] }
log = "0.4.19"
tokio = { version = "1.32.0" }
tokio-stream = "0.1.14"

debounced = { git= "https://github.com/polytope-labs/debounced", branch = "main"}

primitives = { package = "tesseract-primitives", path = "../../primitives" }
pallet-ismp.workspace = true
pallet-ismp-relayer.workspace = true
ismp-demo.workspace = true
ismp-rpc.workspace = true
ismp.workspace = true
reconnecting-jsonrpsee-ws-client.workspace = true

[features]
testing = []
