[package]
name = "beacon-kit-prover"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
reqwest = { version="0.11.14", features=["json"]}
tokio = { workspace = true, features = ["sync"] }
serde = { workspace = true, default-features = true, features = ["derive"] }
tracing = "0.1.40"
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main" }
sync-committee-primitives = { workspace = true, default-features = true }
beacon-kit-verifier = { workspace = true }
async-trait = "0.1.77"
primitive-types = { workspace = true, default-features = true, features = ["serde_no_std", "impl-codec"] }