[package]
name = "ismp-sync-committee"
version = "0.1.0"
edition = "2021"
description = "Ismp consensus client for the Beacon chain's sync-committee"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
# polytope labs
ismp = { git = "https://github.com/polytope-labs/ismp-rs", branch="main", default-features = false }
sync-committee-primitives = { git="https://github.com/polytope-labs/sync-committee-rs", branch="main", default-features = false }
sync-committee-verifier = { git="https://github.com/polytope-labs/sync-committee-rs", branch="main", default-features = false }
patricia-merkle-trie = { package = "ethereum-trie", git ="https://github.com/polytope-labs/ethereum-trie", branch = "main", default-features = false }
pallet-ismp = { git = "https://github.com/polytope-labs/substrate-ismp.git", branch = "main", default-features = false }

# crates.io
trie-db = { version= "0.24.0", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
alloy-rlp = { version = "0.3.2", default-features = false }
alloy-primitives = { version = "0.3.1", default-features = false, features = ["rlp"] }
hex = { version = "0.4.3", default-features = false }
hex-literal = "0.3.4"
alloy-rlp-derive = "0.3.2"
ethabi = { version = "18.0.0", features = ["rlp", "parity-codec"], default-features = false }
hash256-std-hasher = { version = "0.15.2", default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

frame-support = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
frame-system = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-trie = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-io = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-core = {git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }

[dev-dependencies]
ethers = "2.0.3"
tokio = { version = "1.27.0", features = ["full"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "ismp/std",
    "patricia-merkle-trie/std",
    "trie-db/std",
    "hash-db/std",
    "alloy-rlp/std",
    "alloy-primitives/std",
    "ethabi/std",
    "hash256-std-hasher/std",
    "hex/std",
    "sync-committee-primitives/std",
    "sync-committee-verifier/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-runtime/std",
    "sp-core/std",
    "pallet-ismp/std",
]

goerli = ["sync-committee-verifier/goerli", "sync-committee-primitives/goerli"]
mainnet = ["sync-committee-verifier/mainnet", "sync-committee-primitives/mainnet"]
