[package]
name = "pallet-messaging-fees"
version = "0.1.0"
description = "FRAME pallet for incentivizing hyperbridge messaging relayers with rewards"
authors = ["Polytope Labs <hello@polytope.technology>"]
edition = "2021"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
pallet-ismp = { workspace = true, default-features = false }
ismp = { workspace = true, default-features = false }
pallet-ismp-host-executive = { workspace = true, default-features = false }
pallet-hyperbridge = { workspace = true, default-features = false }
hyperbridge-client-machine =  { workspace = true, default-features = false }
pallet-ismp-relayer = { workspace = true, default-features = false }
crypto-utils = { workspace = true, default-features = false }
log = { workspace = true }

[dependencies.polkadot-sdk]
workspace = true
features = ["frame-support", "frame-system", "sp-runtime", "pallet-session", "sp-application-crypto"]

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "polkadot-sdk/std",
    "pallet-ismp/std",
    "pallet-ismp-relayer/std",
    "ismp/std",
    "hyperbridge-client-machine/std",
    "pallet-ismp-host-executive/std",
    "pallet-hyperbridge/std",
    "polkadot-sdk/sp-application-crypto",
    "crypto-utils/std",
    "log/std",
]
runtime-benchmarks = ["polkadot-sdk/runtime-benchmarks"]
try-runtime = ["polkadot-sdk/try-runtime"]
