[package]
name = "tesseract-evm"
version = "0.1.0"
edition = "2021"
description = "EVM primitives for ISMP messaging relay"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[build-dependencies]
anyhow = { workspace = true }
ethers-contract-abigen = { workspace = true }

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
anyhow = { workspace = true }
primitive-types = { workspace = true, default-features = true }
futures = "0.3.28"
async-trait = "0.1.71"
parking_lot = "0.12.1"
serde_json = "1.0.105"
hex-literal = { version = "0.4.1" }
sp-core = { workspace = true, features = ["full_crypto"] }
log = "0.4.19"
ethers = { workspace = true, features = ["rustls"] }
ethabi = { workspace = true, features = ["full-serde"] }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
tokio-stream = { workspace = true }
reqwest-retry = "0.3.0"
reqwest-middleware = "0.2.4"
async-recursion = "1.0.5"
superchain-registry = { version = "0.11", default-features = false }
op-alloy-genesis = "=0.6.2"                                          # need to pin this transitive dependency
jsonrpsee = { workspace = true, features = ["ws-client"] }

ismp-solidity-abi = { workspace = true, default-features = true }
beefy-verifier-primitives = { workspace = true, default-features = true }
pallet-ismp = { workspace = true, default-features = true }
ismp = { workspace = true, default-features = true }
pallet-ismp-rpc = { workspace = true, default-features = true }
geth-primitives = { workspace = true, default-features = true }
ismp-sync-committee = { workspace = true, default-features = true }
ethereum-triedb = { workspace = true, default-features = true }
mmr-primitives = { workspace = true, default-features = true }
evm-state-machine = { workspace = true, default-features = true }
tesseract-primitives = { workspace = true, default-features = true }
merkle-mountain-range = { workspace = true, default-features = true }
ismp-testsuite = { workspace = true, default-features = true }
reconnecting-jsonrpsee-ws-client = { workspace = true, default-features = true }
pallet-ismp-host-executive = { workspace = true, default-features = true }
serde-hex-utils = { workspace = true, default-features = false }
tendermint-prover = {workspace =  true, default-features = false}
ibc = {workspace = true, default-features = false }
ics23 = { workspace = true, default-features = false }
tendermint-ics23-primitives = { workspace = true, default-features = false }
prost = { workspace = true, default-features = false }
cometbft = {workspace = true, default-features = false}
tendermint-primitives = {workspace = true, default-features = false}

[dependencies.polkadot-sdk]
workspace = true
default-features = true
features = ["sp-mmr-primitives", "frame-support"]

[dependencies.codec]
package = "parity-scale-codec"
version = "3.2.2"
features = ["derive"]

[dev-dependencies]
alloy-rlp = { workspace = true, default-features = true }
alloy-rlp-derive = { workspace = true, default-features = true }
alloy-primitives = { workspace = true, default-features = true }
hex = "0.4.3"
dotenv = "0.15.0"

[features]
testing = []
