[package]
name = "ismp-testsuite"
version = "0.1.0"
edition = "2021"
description = "Test suite for  ISMP"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
ismp = { path = "../core" }
primitive-types = "0.12.1"
codec = { package = "parity-scale-codec", version = "3.1.3" }
sp-core = "20.0.0"
