[package]
name = "ismp-solidity-abi"
version = "0.1.1"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]
description = "Generated rust types for the ISMP solidity ABI"
publish = false

[dependencies]
primitive-types = { workspace = true }
anyhow = { workspace = true, default-features = true }
ismp = { workspace = true }

alloy-sol-types = { workspace = true }
alloy-sol-macro = { workspace = true }
alloy-primitives = { workspace = true }
alloy-contract = { workspace = true }
alloy-provider = { workspace = true }
alloy-network = { workspace = true }
alloy-transport = { workspace = true }

mmr-primitives = { workspace = true, default-features = true, optional = true }
merkle-mountain-range = { workspace = true, default-features = true, optional = true }
beefy-verifier-primitives = { workspace = true, default-features = true, optional = true }

[dependencies.polkadot-sdk]
workspace = true
optional = true
features = ["sp-consensus-beefy"]

[features]
default = ["beefy", "std"]
std = [
    "primitive-types/std",
    "anyhow/std",
    "ismp/std",
    "alloy-sol-types/std",
    "alloy-primitives/std",
]
beefy = [
    "merkle-mountain-range",
    "polkadot-sdk",
    "beefy-verifier-primitives",
    "mmr-primitives",
]
