[package]
name = "ismp-parachain-inherent"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
async-trait = { version = "0.1.63" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = [ "derive" ] }
anyhow = "1.0.57"

# Substrate
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }

# Cumulus
cumulus-primitives-core = {  git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
cumulus-relay-chain-interface = {  git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }

# polytope-labs
ismp = { path = "../../core" }

# local
ismp-parachain = { path = "../" }
ismp-parachain-runtime-api = { path = "../runtime-api" }
