[package]
name = "tesseract-substrate-evm"
version = "0.1.0"
edition = "2024"
description = "Substrate EVM client for ISMP messaging relay"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[dependencies]

anyhow = { workspace = true }
async-trait = "0.1.71"
futures = "0.3.28"
primitive-types = { workspace = true, default-features = true }
sp-core = { workspace = true, features = ["full_crypto"] }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
subxt = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.2.2", features = [
    "derive",
] }

ismp = { workspace = true, default-features = true }
tesseract-primitives = { workspace = true, default-features = true }
tesseract-evm = { workspace = true, default-features = true }
tesseract-substrate = { workspace = true, default-features = true }
evm-state-machine = { workspace = true, default-features = true }
pallet-ismp-host-executive = { workspace = true, default-features = true }
config = "0.15.11"
serde = { version = "1.0.219", features = ["derive"] }

[dependencies.polkadot-sdk]
workspace = true
default-features = true
features = ["sp-runtime"]
