[package]
name = "bsc-pos-prover"
version = "0.1.0"
edition = "2021"
description = "Prover for Binance Smart Chain Network's Consensus Protocol"
authors = ["Polytope Labs <hello@polytope.technology>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bsc-pos-verifier = { path= "../verifier" }
anyhow = "1.0.68"
primitive-types = { version = "0.12.1", features = ["serde", "impl-codec"] }
ethers = { workspace = true, features = ["ws"] }
ismp = { path = "../../../ismp/core" }
sp-core = { workspace = true }
sync-committee-primitives  = { path = "../../sync-committee/primitives" }
geth-primitives = { path = "../../geth-primitives" }

[dev-dependencies]
tokio = { version = "1.32.0", features = ["macros"] }
dotenv = "0.15.0"
