[package]
name = "ismp-rpc"
description = "RPC apis for pallet-ismp"
edition = "2021"
version = "0.1.0"
authors = ["Polytope Labs <hello@polytope.technology>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
hex-literal = { version = "0.3.3" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.45"
ismp = { package = "ismp", path = "../core" }
pallet-ismp = { path = "../pallet" }
ismp-runtime-api = { path = "../runtime-api" }


frame-system = { workspace = true, default-features = true }
sc-client-api = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
