[package]
name = "pallet-intents-coprocessor"
version = "2506.2.0"
edition = "2021"
description = "Pallet intent coprocessor is responsible for intent auctions & governance of intent gateway protocol"
authors = ["Polytope Labs <hello@polytope.technology>"]
license = "Apache-2.0"
repository = "https://github.com/polytope-labs/hyperbridge"
homepage = "https://docs.hyperbridge.network/developers/polkadot/intents"
documentation = "https://docs.rs/pallet-intents"
keywords = [
    "substrate",
    "polkadot-sdk",
    "ISMP",
    "interoperability",
    "intents",
]
readme = "README.md"

[dependencies]
sp-io = { workspace = true }

primitive-types = { workspace = true }
log = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
anyhow = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }

ismp = { workspace = true }
pallet-ismp = { workspace = true }

[dependencies.polkadot-sdk]
workspace = true
features = ["frame-support", "frame-system", "sp-runtime", "sp-core", "pallet-balances", "pallet-timestamp"]

[dev-dependencies]
ismp-testsuite = { workspace = true }

[features]
default = ["std"]
std = [
    "polkadot-sdk/std",
    "primitive-types/std",
    "ismp/std",
    "log/std",
    "scale-info/std",
    "anyhow/std",
    "alloy-primitives/std",
    "sp-io/std",
    "pallet-ismp/std",
]
runtime-benchmarks = [
    "polkadot-sdk/frame-benchmarking",
    "polkadot-sdk/runtime-benchmarks",
]
try-runtime = ["polkadot-sdk/try-runtime"]
